apiVersion: v1
kind: PersistentVolume
metadata:
  name: upskilling-pv-volume
spec:
  storageClassName: managed-csi
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/storage"