apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: upskilling-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: managed-csi
  resources:
    requests:
      storage: 1Gi